### ISSUE TITLE
SDL fails to compile on Mac OS 10.5 Leopard

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#31]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/31/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2007-12-17 05:23:18:

When processing the compilation script on Mac OS 10.5, SDL fails to compile, producing these error messages:

/bin/sh ./libtool --mode=compile gcc -I/Users/Josef/chocolate-doom/install/include/SDL   -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/audio/macosx/SDL_coreaudio.c  -o build/SDL_coreaudio.lo
gcc -I/Users/Josef/chocolate-doom/install/include/SDL -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/audio/macosx/SDL_coreaudio.c  -fno-common -DPIC -o build/.libs/SDL_coreaudio.o
./src/audio/macosx/SDL_coreaudio.c: In function 'Core_CloseAudio':
./src/audio/macosx/SDL_coreaudio.c:159: error: storage size of 'callback' isn't known
./src/audio/macosx/SDL_coreaudio.c:172: error: 'kAudioUnitProperty_SetInputCallback' undeclared (first use in this function)
./src/audio/macosx/SDL_coreaudio.c:172: error: (Each undeclared identifier is reported only once
./src/audio/macosx/SDL_coreaudio.c:172: error: for each function it appears in.)
./src/audio/macosx/SDL_coreaudio.c: In function 'Core_OpenAudio':
./src/audio/macosx/SDL_coreaudio.c:203: error: storage size of 'callback' isn't known
./src/audio/macosx/SDL_coreaudio.c:224: error: 'kAudioUnitComponentType' undeclared (first use in this function)
./src/audio/macosx/SDL_coreaudio.c:225: error: 'kAudioUnitSubType_Output' undeclared (first use in this function)
./src/audio/macosx/SDL_coreaudio.c:226: error: 'kAudioUnitID_DefaultOutput' undeclared (first use in this function)
./src/audio/macosx/SDL_coreaudio.c:256: error: 'kAudioUnitProperty_SetInputCallback' undeclared (first use in this function)
make: *** [build/SDL_coreaudio.lo] Error 1

Following the instructions located at http://www.nabble.com/SDL-not-building-on-OS-X-10.5--28Leopard-29---to13426719.html does not affect the compile (although those patches appear to be for 1.2.12 rather than the 1.2.11 the script is trying to compile).
