### ISSUE TITLE
man/simplecpp is not Python3 compatible.

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#282]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/282/) on Sourceforge by [mikeshere](https://sourceforge.net/u/mikeshere/profile/), 2013-10-14 02:14:26.287000:

At the very least, Gentoo and Arch Linux use Python 3.x as the default Python interpreter (gives some importance to the issue IMO), so generating the manual pages results in the following error:

./simplecpp -DDOOM -DPRECOMPILED < INSTALL.template > INSTALL.doom
Traceback (most recent call last):
  File "./simplecpp", line 226, in <module>
    parse_stream(sys.stdin)
  File "./simplecpp", line 73, in parse_stream
    result = read_block(stream, False)
  File "./simplecpp", line 220, in read_block
    for key, value in defines.iteritems():
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'

The included patch resolves this issue; it's a simple one-line fix that works on both Python 2.7 and 3.x.
